version: "3.1"

services:
  firestore-emulator:
    build:
      context: .
      dockerfile: docker/firestore-emulator/Dockerfile
    command: firebase emulators:start --only firestore --project ${FIRESTORE_PROJECT_ID:-simple-alert-line-bot}
    ports:
      - 8085:8085
    environment:
      FIRESTORE_PROJECT_ID: simple-alert-line-bot
    volumes:
      - ./firebase.json:/app/firebase.json:ro
