version: "3.1"

services:
  firestore-emulator:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    command: gcloud beta emulators firestore start --host-port=0.0.0.0:8080
    ports:
      - 8080:8080
    environment:
      FIRESTORE_PROJECT_ID: simple-alert-line-bot
